### ISSUE TITLE
Insufficient funds [needed] => 

### ISSUE THREAD

**Issue by elizondobanderas** [blockchain/service-my-wallet-v3#109]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*
blockchain-wallet-service version 0.21.3

I made an new blockchain account with 150$ bitcoins inside, 
I have blockchain api to with permission to send bitcoins 
I logged in successfully  on my localhost wallet service vps
**the problem is :** When I try to send bitcoin I get 
**Array ( [error] => Insufficient funds [needed] => 0.0031 [available] => 0 )**
And as I told you I have 150$ bitcoins,
I sent my issue to support they told me : 

> **Hi,
> 
> This error, "Insufficient funds", usually comes when you either have many pending transactions within the wallet (Which you will need to wait to confirm), or you have many small amounts of bitcoin in many addresses in the wallet (which you would need to try and consolidate to send normally).
> 
> Best,**

But there's nothing pending and my account is fully new also I tried again when my available bitcoins in my account get 100% confirmed , Also same issue 
I tried with another account same problem

**Comment by Lanskih90** [comment]
I have the same problem:
Log error:
1463747263347 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC

My account balance is $5!

**Comment by elizondobanderas** [comment]
I think they hasten with this upgrade , they must fully check it before release

**Comment by Lanskih90** [comment]
I agree with you! A lot of problems in new release!

**Comment by Lanskih90** [comment]
@elizondobanderas - you tried to use the "Consolidating Addresses"?

**Comment by Lanskih90** [comment]
Strange how it works! error loops! 
I execute the script send money once. I look in the log there are more than 20 errors

Log errors: 
1463753732167 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0.00015202BTC
1463753737019 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0.00015202BTC
1463753746468 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC
1463753752667 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC
1463753754994 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC
1463753757946 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC
...
...
...
1463753773125 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC
1463753774147 - error: Insufficient funds. Value Needed 0.0002BTC. Available amount 0BTC

**Comment by Lanskih90** [comment]
> Can you try making a new account in your wallet, and then transferring all funds in your wallet to this new account. Then, in your api call, add an &from=1 (to denote the second account in your wallet that you just created). Or, if this is the third account in the wallet, it would be &from=2

@elizondobanderas - try it, it helped me!

**Comment by elizondobanderas** [comment]
@Lanskih90  What do you mean with Opening a new account inside my wallet?
You mean create new address and transfer bitcoins from the main default address to the new created address?

**Comment by elizondobanderas** [comment]
The Problem is Resolved, Thanks.
The solution  is : 
create new address in your wallet and transfer bitcoins from your old address to the new one(any amount)
then in your api url add : &from=1

so it's be like that : 
 http://127.0.0.1:3030/merchant/$guid/payment?password=$password&to=$address&amount=$amount&api_code=API&from=1

Then It's gonna work.

Thanks for everyone @Lanskih90  @tuzzolo @colkito @zootreeves

**Comment by amibenson** [comment]
What @elizondobanderas suggested had worked, but you can also just add "from=0" without creating a new address. It worked for me!

**Comment by veitsi** [comment]
this bug is still active, i use server from node.js and error is the same
