### ISSUE TITLE
Balance not updating correctly

### ISSUE THREAD

**Issue by jbudiman** [blockchain/service-my-wallet-v3#18]
Hi there, 

It seems that the /balance method is not updating Bitcoin balance correctly after you have performed /payment. 

The only way to get it to update the balance properly is to perform /login again. But currently there is an issue where the service crashed if you try to login if you are already logged in.

This is the exit error message when I am trying to perform /payment if you are logged in twice:

```
/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:207
  if (state.ended)
           ^
TypeError: Cannot read property 'ended' of undefined
    at DuplexWrapper.Writable.write (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:207:12)
    at DuplexWrapper.Writable.end (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:426:10)
    at API.request (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/api.js:91:30)
    at API.retry (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/api.js:118:12)
    at API.getHistory (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/api.js:207:15)
    at Wallet.getHistory (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/blockchain-wallet.js:391:21)
    at WebSocket.onMessage (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/wallet.js:236:23)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/ws/lib/WebSocket.js:816:10)
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/ws/lib/Receiver.js:477:18
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/ws/lib/Receiver.js:361:7
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/node_modules/ws/lib/PerMessageDeflate.js:238:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at afterTransform (_stream_transform.js:99:5)
```

**Comment by jtormey** [comment]
Hi @jbudiman, the problem with logging in multiple times was fixed earlier today, as well as the issue that was causing the exit error message above. Could you try again on the latest version (v0.11.0 for service-my-wallet-v3, and v3.4.0 for blockchain-wallet-client) to see if that has fixed the balance update problem? Thanks.

**Comment by jbudiman** [comment]
Thanks @jtormey, I can see there are no more exit error from multiple logins. Awesome!
However, the balance problem still persist. I believe this may have something to do with caching.

To replicate the issue:
- When my wallet receives a payment. 
Balance seems to be updated immediately.
- Individual test on ```/payment```. 
Balance seems to be updated immediately every time I execute ```/payment```.
- However, when the wallet receives a payment and then immediately perform /payment (busy traffic), Balance isn't updated correctly. Doing ```/login``` before ```/balance``` does not fix it. Restarting blockchain-wallet-service and ```/login``` again seems to fix the balance.

**Comment by TOSHIAKI1331** [comment]
43574

**Comment by jtormey** [comment]
As of v0.14.3, calling `/login` on an already logged in wallet will refresh the balance. I'm also looking into ways to make the automatic balance updating more reliable.
