### ISSUE TITLE
sending payment

### ISSUE THREAD

**Issue by html5-ninja** [blockchain/service-my-wallet-v3#27]
trying to do a payment I got this 

 failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error

but work perfectly for login to the wallet

**Comment by jtormey** [comment]
What version of the service are you using? Did you install it recently or a while ago? One of our dependencies (my-wallet-v3) used to rely on streams for network calls, which caused us some issues. This was fixed in the upgrade to v3.4. Can you try again after a fresh install?

**Comment by html5-ninja** [comment]
I just installed the wallet few weeks ago , 
blockchain-wallet-service -V
0.13.0

I will try to update and see this fix the problem , thank you

**Comment by html5-ninja** [comment]
I ve reinstalled de service 
now 
blockchain-wallet-service -V
0.14.0

but still have the same problem 

Message: file_get_contents(http://localhost:2307/....): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error

I'm using php with nginx server

**Comment by jtormey** [comment]
Ok, so the error you're getting is actually caused by PHP, not the local service (PHP isn't able to get the request out at all). I'm guessing that the request is failing because of an encoding problem with the recipient json object in the url.

Before making the request, be sure to properly encode the url with [urlencode()](http://docs.php.net/manual/en/function.urlencode.php). And if that doesn't work, try using [cURL](http://www.sitepoint.com/using-curl-for-remote-requests/) rather than `file_get_contents()` to call the api.

**Comment by html5-ninja** [comment]
ok , at least now with curl I can get the content , but now I got this "{"error":"Missing coins to spend"}"
what it mean , seriously this new API has a lack of documentation , we are urged to merge to the new api in few day but nothing work properly

**Comment by jtormey** [comment]
"Missing coins to spend" means that one of the addresses you are trying to send from has no spendable outputs. More specifically, the address has either never been sent bitcoin or none of the btc that make up it's balance have been confirmed.

To check an address for unspent outputs, go to `https://blockchain.info/unspent?active=$address`.

**Comment by html5-ninja** [comment]
Ok I will check that ,  thank you

**Comment by html5-ninja** [comment]
well I tested all the address I have  on my alpha wallet 
with a lot of confirmed transaction and that contain some BTC , still not working , any way thank you, I'm done for today , I think it's not the good moment to switch to the new api

**Comment by jtormey** [comment]
Sorry you're still having issues, I'll play around with the payment endpoint to see if I can reproduce.

**Comment by html5-ninja** [comment]
just for information , even getting wallet balance is total wrong 
{"balance":0} , which false

**Comment by jtormey** [comment]
Thanks for letting me know

**Comment by Raiymbek** [comment]
i have the same issue.
Thanks for html5-ninja. Balance is total wrong. 
{"balance":0} , which false

**Comment by html5-ninja** [comment]
apparently this is related to beta tester , it work if you try with new
wallet

2016-02-08 12:50 GMT+01:00 Raiymbek <notifications@github.com>:
