### ISSUE TITLE
Main wallet password incorrect in wallet API - Critical Issue

### ISSUE THREAD

**Issue by saniyavohra** [blockchain/service-my-wallet-v3#320]
I am using ( https://github.com/blockchain/service-my-wallet-v3#list-active-hd-accounts) service to retrieve my wallet balance. It was working fine. Then, I changed my wallet password and again with changed password I made a call to this service. I got this error. ({"error":"Main wallet password incorrect"}).

Then , again I change the password from new to old one and I made a call to this service. Everything started working.

My question is blockchain wallet service api doesn't update the wallet password? So, What if I would have forgot my old password? I would have never able to use this api again or need to create different wallet with password which I should never change? And What if I want to use this api and in between I change my password? It will stop working in my website.

Note : I am locally using the service using url - http://localhost:3000/merchant/{my-wallet-guid}/accounts?password={my-wallet-password}

Please help?
Thanks

service-my-wallet-v3 : v0.26.0
NodeJS : v8.9.3

**Comment by Uter1007** [comment]
For me the solution was to use a more simple pw. I think it could need escaping or other special treatment...

**Comment by saniyavohra** [comment]
Its not about using simple pw. Problem persist when we change password and use wallet api services. These services still works only with old password and not the new one.

**Comment by jcfrane** [comment]
Is this fixed?

**Comment by jtormey** [comment]
Correct, this isn't an encoding issue. It looks like what's happening is a caching problem.

The service caches the encrypted wallet data in memory (to avoid the cost of an extra API call whenever a request is made). However, this cached data is currently not invalidated when a password change happens, meaning the old password will still work but not the new one.

For now, a potential workaround is to restart the service after a password change (which clears the cache). I will look into a way to invalidate the cache automatically when the password is changed, so that a restart is not necessary.

**Comment by jtormey** [comment]
Fixed in v0.26.3

**Comment by jcfrane** [comment]
Thanks!

**Comment by aminNazarii** [comment]
@jtormey I am on v0.26.3 but still have this issue. i was changed my pw on my panel after logged in

**Comment by Theeeus** [comment]
Has someone solved this issue? I'm having the same problem but nothing suggested above seems to work
